# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  build:
    docker:
      # specify the version
      #- image: circleci/golang:1.13
      - image: couchdb:3.1.1
        environment:
          COUCHDB_USER: admin
          COUCHDB_PASSWORD: password
       
    working_directory: /go/src/github.com/intorch/config
    
    steps:
      - checkout
       
      - run: curl https://dl.google.com/go/go1.15.6.linux-amd64.tar.gz --output go.tar.gz
      - run: tar -C /usr/local -xzf go.tar.gz
      - run: ln -s /usr/local/go/bin/go /usr/bin/go
       
      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
